{{- if .Values.public }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
{{- include "helpers.metadata" . | indent 2 }}
spec:
  tls:
  - hosts:
    - {{ .Values.host }}
  rules:
  - host: {{ .Values.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.name | quote }}
          servicePort: http
{{- end }}
